on:
  push:
    tags:
      - 'v*.*.*'
name: Build Extension
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - name: Increment VSIX version
        id: vsix_version
        uses: timheuer/vsix-version-stamp@v2
        with:
          manifest-file: .vsixmanifest
      - uses: lannonbr/vsce-action@4.0.0
        with:
          args: "package -o extension_${{ github.ref_name }}.vsix"
      - uses: actions/upload-artifact@v4
        with:
          name: Release ${{ github.ref_name }}
          path: extension_${{ github.ref_name }}.vsix
