on:
  push:
    tags:
      - 'v*.*.*'
name: Build Extension
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - uses: lannonbr/vsce-action@4.0.0
        with:
          args: "package -o extension_${{ github.ref_name }}.vsix"
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "extension_${{ github.ref_name }}.vsix"
