on:
  push:
    tags:
    - '[0-9]+.[0-9]+.[0-9]+'
    - '[0-9]+.[0-9]+.[0-9]+rc[0-9]+'
name: Build Extension
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: tsc -p ./
      - name: Set version to ${{ github.ref_name }}
        uses: restackio/update-json-file-action@2.1
        with:
          file: package.json
          fields: "{'version': '${{ github.ref_name }}'}"
      - uses: lannonbr/vsce-action@4.0.0
        with:
          args: "package -o extension_${{ github.ref_name }}.vsix"
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "kitsuniru_${{ github.ref_name }}.vsix"
